    $(document).ready(function(){
       $(".blurb").click(function(){
            $(".text1").slideToggle('slow');
            $(".text").slideToggle('slow');
            $(".text2").hide();
            $(".text3").hide();
            $(".text4").hide();
            $(".cal").slideToggle('slow');
            $(".exec").slideToggle('slow');
            $(".events").slideToggle('slow');
            $(".blurb").toggleClass("blue");
          });
       $(".exec").click(function(){

            $(".text1").slideToggle('slow');
            $(".text2").slideToggle('slow');
            $(".text").hide();
            $(".text3").hide();
            $(".text4").hide();
            $(".blurb").slideToggle('slow');
            $(".cal").slideToggle('slow');
            $(".events").slideToggle('slow');
            $(".exec").toggleClass("blue");
       });
       $(".cal").click(function(){
            $(".text1").slideToggle('slow');
            $(".text3").slideToggle('slow');
            $(".text").hide();
            $(".text2").hide();
            $(".text4").hide();
            $(".blurb").slideToggle('slow');
            $(".exec").slideToggle('slow');
            $(".events").slideToggle('slow');
            $(".cal").toggleClass("blue");
       });
       $(".events").click(function(){
            $(".text1").slideToggle('slow');
            $(".text4").slideToggle('slow');
            $(".text").hide();
            $(".text2").hide();
            $(".text3").hide();
            $(".blurb").slideToggle('slow');
            $(".exec").slideToggle('slow');
            $(".cal").slideToggle('slow');
            $(".events").toggleClass("blue");
       });
     });